---
default_stages: [commit, push]
default_language_version:
  python: python3
minimum_pre_commit_version: "1.20.0"
repos:
  - repo: local
    hooks:
      - id: render_all
        name: Render docker-compose files
        language: python
        entry: ./render_all.sh
        always_run: true
        additional_dependencies:
          - httpx
          - jsonschema
          - PyYAML
          - semver
          - jinja2
      - id: pre_commit_insert_usage
        name: Insert Usage help in README.md
        language: python
        entry: ./scripts/pre_commit_insert_usage.py
        additional_dependencies:
          - httpx
          - jsonschema
          - PyYAML
          - semver
          - jinja2
