name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]
        compose_version:
          - 1.29.2
          - 1.29.1
          - 1.29.0
          - 1.28.6
          - 1.28.5
          - 1.28.4
          - 1.28.3
          - 1.28.2
          - 1.28.0
          - 1.28.0-rc3
          - 1.28.0-rc2
          - 1.28.0-rc1
          - 1.27.4
          - 1.27.3
          - 1.27.2
          - 1.27.1
          - 1.27.0
          - 1.27.0-rc4
          - 1.27.0-rc3
          - 1.27.0-rc2
          - 1.27.0-rc1
          - 1.26.2
          - 1.26.1
          - 1.26.0
          - 1.26.0-rc5
          - 1.26.0-rc4
          - 1.25.5
          - 1.25.5-rc1
          - 1.26.0-rc3
          - 1.26.0-rc2
          - 2
    concurrency:
      group: ${{ github.event.pull_request.number || github.ref }}-${{ matrix.compose_version }}-${{ matrix.on }}
      cancel-in-progress: true
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - if: matrix.compose_version != '2'
        name: "Update Docker compose"
        env:
          COMPOSE_VERSION: ${{ matrix.compose_version }}
        run: |
          sudo rm -rf $(command -v docker-compose)
          curl -fsSL "https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o docker-compose
          chmod +x docker-compose
          sudo mv docker-compose /usr/local/bin/docker-compose
      - if: matrix.compose_version == '2'
        name: "Update Docker CLI and Docker compose"
        run: |
          sudo rm "$(command -v docker)";
          curl -fsSL https://test.docker.com | sh;
          echo "Installed docker"
          sudo rm -rf $(command -v docker-compose)
          TMP_DIR="$(mktemp -d)"
          curl -fsSL https://github.com/docker/compose-cli/releases/download/v2.0.0-beta.4/docker-compose-linux-amd64 -o "${TMP_DIR}/docker-compose-v2"
          chmod +x "${TMP_DIR}/docker-compose-v2"
          echo -e '#!/bin/bash\nexec docker-compose-v2 compose "${@}"' > "${TMP_DIR}/docker-compose"
          chmod +x "${TMP_DIR}/docker-compose"
          export PATH="${TMP_DIR}:${PATH}"
          echo "PATH=${PATH}" >> $GITHUB_ENV
          echo "Installed docker-compose v2"
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - uses: pre-commit/action@v2.0.3
      - run: pip install -r requirements.txt
      - run: pytest tests/ -vvvv -s --color=yes
