name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - run: pip install httpx jsonschema PyYAML semver jinja2
      - run: |
          docker run --rm "debian:buster-slim" bash -c 'numfmt --to iec $(echo $(($(getconf _PHYS_PAGES) * $(getconf PAGE_SIZE))))'
      - run: |
          docker --version
          docker-compose --version
      - run: |
          mkdir ./dags ./logs ./plugins;
          echo -e "AIRFLOW_UID=$(id -u)\nAIRFLOW_GID=0" > .env
      - run: ./render_all.sh
      - run: ./test_all.sh
